### ISSUE TITLE
Printing tables with ints: normalize error

### ISSUE THREAD

**Issue by kjam** [onyxfish/agate#411]
Hey @onyxfish,

I found this error when working with some old code that worked in 1.0.0

```
/home/katharine/.virtualenv/bkreview/lib/python2.7/site-packages/agate/preview.pyc in print_table(table, max_rows, max_columns, output)
     65 
     66         if isinstance(c.data_type, Number):
---> 67             max_places = max_precision(c[:max_rows])
     68             number_formatters.append(make_number_formatter(max_places))
     69         else: 

/home/katharine/.virtualenv/bkreview/lib/python2.7/site-packages/agate/utils.pyc in max_precision(values)
    147             continue
    148 
--> 149         places = value.normalize().as_tuple().exponent * -1
    150 
    151         if places > max_places:

AttributeError: 'int' object has no attribute 'normalize'
```

You can use the attached code to replicate (or let me know if I'm missing something :) )

thanks!

https://gist.github.com/kjam/d246a89563b4039d447c
[corruption_perception_index.xlsx](https://github.com/onyxfish/agate/files/82597/corruption_perception_index.xlsx)
[unicef_oct_2014.xlsx](https://github.com/onyxfish/agate/files/82598/unicef_oct_2014.xlsx)
